config/routes.rb
DareProject::Application.routes.draw do

  resources :user, :except=>[:new,:create]
  resources :submit
  resources :dare
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
   get 'users/sign_out', :to => 'devise/sessions#destroy'
 end
  root :to => "home#index"

end

app/models/dare.rb
class Dare < ActiveRecord::Base
  attr_accessible :title, :attached_video, :description, :end_time,:amount_pledged
  has_many :submits
  belongs_to :user
  has_attached_file :attached_video,:storage => :s3,
       :s3_credentials => "#{Rails.root}/config/s3.yml",
       :path => "/:filename",
       :url  => ":s3_sg_url",
       :use_timestamp => false
       
       def attached_video_url
           if attached_video.file?
            attached_video.url
          else
            nil
        end    
      end
end

app/models/submit.rb
class Submit < ActiveRecord::Base
  belongs_to :user
  belongs_to :dare
  attr_accessible :attached_video
  has_attached_file :attached_video,:storage => :s3,
        :s3_credentials => "#{Rails.root}/config/s3.yml",
        :path => "/:filename",
        :url  => ":s3_sg_url",
        :use_timestamp => false
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  
  # :lockable, :timeoutable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable, :confirmable ,:omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:provider, :uid
  has_many :dares
  has_many :submits
  # attr_accessible :title, :body
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                           )
    end
    user
  end
  
  
  def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dare_controller.rb
class DareController < ApplicationController
  def index #this should be the home page where you can see all the dares
    @all_dares = Dare.all 
  end

  def show
    @dare = Dare.find(params[:id])
    @all_submits = @dare.submits
  end

  def new
    if user_signed_in?
      @dare = Dare.new
    else
      redirect_to new_user_session_path
    end
  end
  
  def create
     if user_signed_in?
     @dare = Dare.new(params[:dare])
     @dare.save
     current_user.dares << @dare
     current_user.save
     redirect_to dare_index_path
    else
      redirect_to new_user_session_path
    end
  end

  def edit
    @dare = Dare.find(params[:id])
  end

  def update
    @dare = Dare.find(params[:id])
  end

  def destroy
    @dare = Dare.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/submit_controller.rb
class SubmitController < ApplicationController
  # this controller is only for logged in users
  before_filter :authenticate_user!
  def index
  end

  def show
  end

  def create
    @submit = Submit.new(params[:submit])
    @dare = Dare.find(params[:id]) 
    @submit.save
    @dare.submits << @submit
    current_user.submits << @submit
    @dare.save
    
    redirect_to "/dare/#{params[:id]}"
    #go back to the dare.id
  end

  def new
    @submit = Submit.new
    @objectId = params[:id]
  end

  def update
  end

  def edit
  end

  def destroy
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!
  def index
    @user = current_user
  end

  def show
    
  end

  def destroy
  end

  def update
  end

  def edit
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    puts request.env["omniauth.auth"]
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dare_helper.rb
module DareHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/submit_helper.rb
module SubmitHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dare/create.html.erb
<h1>Dare#create</h1>
<p>Find me in app/views/dare/create.html.erb</p>

app/views/dare/destroy.html.erb
<h1>Dare#destroy</h1>
<p>Find me in app/views/dare/destroy.html.erb</p>

app/views/dare/edit.html.erb
<h1>Dare#edit</h1>
<p>Find me in app/views/dare/edit.html.erb</p>

app/views/dare/index.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container" align="right">

		

				<a class="brand" href="<%= root_path %>">
					 DareAngels
				</a>		
			<div class="nav-collapse">
			<ul class="nav" id="mainnav">
				<li class="active"><%= link_to 'Dares', dare_index_path %>
				<li ><%= link_to 'About', root_path %>				
			</ul>
			<%if user_signed_in?%>
			<%= current_user.email %>
			<a class="btn btn-large btn-danger" href="<%= destroy_user_session_path %>">
				Sign out
				</a>
			<%else%>
			<a class="btn btn-medium btn-primary" href="<%= new_user_registration_path %>">
				Sign up
				</a>	
			<a class="btn btn-medium btn-primary" href="<%= new_user_session_path %>">
				Sign in
				</a>
			<%end%>
		</div>
		</div> <!-- /container -->

	</div> <!-- /navbar-inner -->

</div> <!-- /navbar -->
</br></br></br></br>
<%= link_to 'Create a Dare', new_dare_path , class: "btn btn-large"%>
<div class= "container" >

 
<div class="row-fluid">	
	<%@c=1%>
<% @all_dares.each do |dare| %>  
	<%if @c==0%>
	<ul class="thumbnails">
	<%end%>
	<%@c=@c+1%>

	<li class="span4">
		<a href="/dare/<%= dare.id %>">
		<div class="thumbnail" style="height:500px;">
			<img src="http://placehold.it/300x200">
			<div class="caption">
				<h3><%= dare.title %></h3>
				<p><%= dare.description %></p>	
				</a>
	</li>
	<%if @c>3%>
	<%@c=0%>
	</ul>
	<%end%>
<% end %>
		



</div>

app/views/dare/show.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=541254549234637";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<script>
  $(document).ready(function() {
    $("#progressbar").progressbar({ value: 37 });
	$("#progressbar2").progressbar({ value: 80 });
  });
  </script>


 	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container" align="right">

			

					<a class="brand" href="<%= root_path %>">
						 DareAngels
					</a>		
				<div class="nav-collapse">
				<ul class="nav" id="mainnav">
					<li class="active"><%= link_to 'Dares', dare_index_path %>
					<li ><%= link_to 'About', root_path %>				
				</ul>
				<%if user_signed_in?%>
				<%= current_user.email %>
				<a class="btn btn-large btn-danger" href="<%= destroy_user_session_path %>">
					Sign out
					</a>
				<%else%>
				<a class="btn btn-medium btn-primary" href="<%= new_user_registration_path %>">
					Sign up
					</a>	
				<a class="btn btn-medium btn-primary" href="<%= new_user_session_path %>">
					Sign in
					</a>
				<%end%>
			</div>
			</div> <!-- /container -->

		</div> <!-- /navbar-inner -->

	</div> <!-- /navbar -->




<header class="well" id="overview">
	</br>	</br>
<div class="container">
<h1>Title: <%= @dare.title %></h1>
<h4>Description: <%= @dare.description %></h4>
</div>
</header>
<div class="span1">
	</div>
	<div class="span9">
<div class="row">
<div class="flowplayer" >
   <video src="<%= @dare.attached_video.url%>"></video>
</div>

<div class="row">
	
<div class="span6" id="progressbar"></div>
<h4 class="span3">3 Days Left!</h4>
</div>
<div class="row">
	
<div class="span6" id="progressbar2"></div>
<h4 class="span3">$250.00 Pledged!</h4>
</div>

<div class="fb-comments " data-href="http://dareangels.herokuapp.com/dare/<%= @dare.id %>" data-num-posts="10" data-width="470"></div>
</div>
</div>


<div class="span5">
<h1>Submits</h1><%= link_to 'Submit video!', "/submit/new?id=#{ @dare.id}",:method => "GET", class: "btn btn-danger btn-small"%>
<% @all_submits.each do |submit| %>
<div class="flowplayer" >
	   <video src="<%= submit.attached_video.url%>"></video>
	</div>
	

<% end %>
</div>

app/views/dare/update.html.erb
<h1>Dare#update</h1>
<p>Find me in app/views/dare/update.html.erb</p>

app/views/home/index.html.erb
<style>
body
{
background-image:url('/assets/rough_diagonal_@2X.png');
background-color:#FFFCA3;
}
</style>
</br></br></br></br>
<div class="container hero-unit">
	<div class="span3">
<h1>DareAngels Prototype</h1>
<h2>Angel investments for devilish dares</h2>
<%= link_to 'Create a Dare', new_dare_path , class: "btn btn-large"%>
<%= link_to 'View all Dares', dare_index_path , class: "btn btn-large"%>
<%if user_signed_in?%>
<%= link_to 'My Profile', user_index_path , class: "btn btn-large"%>
<%= link_to 'Sign Out', destroy_user_session_path , class: "btn btn-large"%>
<%end%>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DareProject</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

<!-- 2. flowplayer -->
<script src="http://releases.flowplayer.org/5.0.0/flowplayer.min.js"></script>

<!-- global options -->
<script>
flowplayer.conf = {
   engine: "html5",
   embed: false,
   swf: "./assets/flowplayer.swf",
   analytics: 'UA-27182341-1'
};
</script>

<!-- 3. skin -->
<link rel="stylesheet" type="text/css"
   href="http://releases.flowplayer.org/5.0.0/skin/minimalist.css" />

<style>
body
{
background-image:url('/assets/rough_diagonal_@2X.png');
background-color:#FFFCA3;
}
</style>



</head>
<body>
<%= yield %>

</body>
</html>

app/views/submit/new.html.erb
<div class="container hero-unit">
<h1>Submit#new</h1>


<%= simple_form_for(@submit, :url => "/submit?id=#{@objectId}",:html=>{:class=>"span5", :mulitpart=>true }) do |f| %>
  	<%= f.input :attached_video, :required => false , :label=> "attachedvideo"%></br></br>

  
  <div class="form-actions">
    <%= f.button :submit, "Upload!", class: "btn btn-large btn-primary" %>
  </div></div>

<% end %>
</div>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/user/index.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container" align="right">
				<a class="brand" href="<%= root_path %>">
					 DareAngels
				</a>		
			<div class="nav-collapse">
			<ul class="nav" id="mainnav">
				<li class="active"><%= link_to 'Dares', dare_index_path %>
				<li ><%= link_to 'About', root_path %>				
			</ul>
			<%if user_signed_in?%>
			<%= current_user.email %>
			<a class="btn btn-large btn-danger" href="<%= destroy_user_session_path %>">
				Sign out
				</a>
			<%else%>
			<a class="btn btn-medium btn-primary" href="<%= new_user_registration_path %>">
				Sign up
				</a>	
			<a class="btn btn-medium btn-primary" href="<%= new_user_session_path %>">
				Sign in
				</a>
			<%end%>
		</div>
		</div> <!-- /container -->

	</div> <!-- /navbar-inner -->

</div> <!-- /navbar -->
</br></br></br></br>

<div class="container" >
<h1>Dares</h1>
<div class="row-fluid">	
	<%@c=1%>
<% @user.dares.each do |dare| %>  
	<%if @c==0%>
	<ul class="thumbnails">
	<%end%>
	<%@c=@c+1%>

	<li class="span4">
		<a href="/dare/<%= dare.id %>">
		<div class="thumbnail" style="height:500px;">
			<img src="http://placehold.it/300x200">
			<div class="caption">
				<h3><%= dare.title %></h3>
				<p><%= dare.description %></p>	
				</a>
	</li>
	<%if @c>3%>
	<%@c=0%>
	</ul>
	<%end%>
<% end %>
	
 </div>
<%= link_to 'Create a Dare', new_dare_path , class: "btn btn-large"%>
<h1> Submits </h1>
<div class="row-fluid">	
	<%@c=1%>
<% @user.submits.each do |submit| %>  
	<%if @c==0%>
	<ul class="thumbnails">
	<%end%>
	<%@c=@c+1%>

	<li class="span4">
		<a href="/dare/<%= submit.id %>">
		<div class="thumbnail" style="height:500px;">
			<img src="http://placehold.it/300x200">
			<div class="caption">
				</a>
	</li>
	<%if @c>3%>
	<%@c=0%>
	</ul>
	<%end%>
<% end %>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/show.html.erb
<h1>Dares</h1>
<table class="table" border="1">
  <tr>
	<th>ID</th>
    <th>title</th>
	<th>description</th>
	<th>video</th>
	
  
  </tr>
 
<% @user.dares.each do |dare| %>
  <tr>
	<td><%= dare.id %></td>
	<td><%= dare.title %></td>
	<td><%= dare.description %></td>
	<td><div class="flowplayer" >
	   <video src="<%= dare.attached_video.url%>"></video>
	</div></td>
	<td><%= link_to 'SHOW', "/dare/#{dare.id}",:method => "GET", class: "btn btn-danger btn-small"%></td>

  </tr>
<% end %>
</table>
	<%= link_to 'Create a Dare', new_dare_path , class: "btn btn-large"%>
 

<h1> Submits </h1>
<table class="table" border="1">
  <tr>
	<th>video</th>
	
  
  </tr>

<% @user.submits.each do |submit| %>
  <tr>
	<td><div class="flowplayer" >
	   <video src="<%= submit.attached_video.url%>"></video>
	</div></td>

  </tr>
<% end %>
</table>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>